import{A as q,S as E,i as u}from"./assets/vendor-db5ad915.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const f=q.create({baseURL:"https://pixabay.com",params:{key:"42310325-d8e2b88bd4f4d7db9639050a5",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:150,page:1}});let P=new E(".image-link",{captionsData:"alt",captionDelay:250});const $=document.querySelector(".form"),g=document.querySelector(".input-name"),l=document.querySelector(".loader"),k=document.querySelector(".gallery"),m=document.querySelector(".load-btn");let h=1,p="",c=0,n=0;$.addEventListener("submit",x);async function x(o){o.preventDefault();const e=g.value.trim();if(e===""){u.show({title:"Error",message:"Please enter a search query"});return}e!==p&&(h=1,p=e),l.classList.add("visible");try{const i=(await f.get("/api/",{params:{q:e}})).data;n=i.totalHits,c=d(i.hits,n,c),d(i.hits,n)}catch(r){console.log("Error fetching data:",r)}finally{l.classList.remove("visible")}}m.addEventListener("click",C);async function C(){const o=g.value.trim();l.classList.add("visible");try{const r=(await f.get("/api/",{params:{q:o,page:h+=1}})).data;d(r.hits),n=r.totalHits,c=d(r.hits,n,c),y(c,n)}catch(e){console.log("Error fetching data:",e)}finally{l.classList.remove("visible")}}function O(o,e,r,i,t,s,a){return`<li class="photo">
  <div class="photo-card">
    <a class="image-link" data-lightbox="image" href="${e}">
    <img class="gallery-image" data-source="${e}"  src="${o}" alt="${r}"></img>
    </a>
    </div>
      <div class="description">
        <p class="description-item"> Likes ${i}</p>
        <p class="description-item"> Views ${t}</p>
        <p class="description-item"> Comments ${s}</p>
        <p class="description-item"> Downloads ${a}</p>

    </div>
  </li>`}function d(o,e,r){return o.length===0?(u.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",messageSize:"25"}),r):(o.forEach(i=>{const{webformatURL:t,largeImageURL:s,tags:a,likes:b,views:v,comments:L,downloads:w}=i,S=O(t,s,a,b,v,L,w);k.insertAdjacentHTML("beforeend",S)}),r+=o.length,P.refresh(),y(r,e),r)}function M(){m.style.visibility="visible"}function z(){m.style.visibility="hidden"}function y(o,e){if(console.log(e),console.log(o),o>=e){u.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"red",messageColor:"white",messageSize:"25"}),z();return}else M()}
//# sourceMappingURL=commonHelpers.js.map
