import{A as E,S as P,i as u}from"./assets/vendor-db5ad915.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const f=E.create({baseURL:"https://pixabay.com",params:{key:"42310325-d8e2b88bd4f4d7db9639050a5",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:150,page:1}});let $=new P(".image-link",{captionsData:"alt",captionDelay:250});const x=document.querySelector(".form"),g=document.querySelector(".input-name"),c=document.querySelector(".loader"),y=document.querySelector(".gallery"),m=document.querySelector(".load-btn");let d=1,h="",n=0,l=0;x.addEventListener("submit",C);async function C(o){o.preventDefault();const t=g.value.trim();if(t===""){u.show({title:"Error",message:"Please enter a search query"});return}y.innerHTML="",d=1,n=0,p(),t!==h&&(d=1,h=t),c.classList.add("visible");try{const i=(await f.get("/api/",{params:{q:t}})).data;l=i.totalHits,n=b(i.hits,l,n)}catch(s){console.log("Error fetching data:",s)}finally{c.classList.remove("visible")}}m.addEventListener("click",k);async function k(){p();const o=g.value.trim();c.classList.add("visible");try{const s=(await f.get("/api/",{params:{q:o,page:d+=1}})).data;l=s.totalHits,n=b(s.hits,l,n),B()}catch(t){console.log("Error fetching data:",t)}finally{c.classList.remove("visible")}}function H(o,t,s,i,e,r,a){return`<li class="photo">
  <div class="photo-card">
    <a class="image-link" data-lightbox="image" href="${t}">
    <img class="gallery-image" data-source="${t}"  src="${o}" alt="${s}"></img>
    </a>
    </div>
      <div class="description">
        <p class="description-item"> Likes ${i}</p>
        <p class="description-item"> Views ${e}</p>
        <p class="description-item"> Comments ${r}</p>
        <p class="description-item"> Downloads ${a}</p>

    </div>
  </li>`}function b(o,t,s){return o.length===0?(u.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",messageSize:"25"}),s):(o.forEach(i=>{const{webformatURL:e,largeImageURL:r,tags:a,likes:v,views:L,comments:w,downloads:S}=i,q=H(e,r,a,v,L,w,S);y.insertAdjacentHTML("beforeend",q)}),s+=o.length,$.refresh(),O(s,t),s)}function M(){m.style.visibility="visible"}function p(){m.style.visibility="hidden"}function O(o,t){if(o>=t){u.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"red",messageColor:"white",messageSize:"25"}),p();return}else M()}function B(){const o=document.querySelector(".photo").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
